version: "3"
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    links:
      - mysql

    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: '12345678'
    volumes:
      - ./nestjs-app:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: CSV

    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql 

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

volumes:
  nestjs-app:
  mysql-data: